name: Bug Report
description: File a bug report.
labels: ["bug"]
# assignees:
# projects:
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your report. Your feedback helps improve The House App for everyone. Thank you!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
      # value:
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        ...
      # value:
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      # placeholder:
      # value:
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: (Only put images/videos in here)
      # value:
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: What are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows
        - Web
        - iOS
        - Android
  - type: input
    id: version-os
    attributes:
      label: What version of that software are you seeing the problem on?
    validations:
      required: false
  - type: dropdown
    id: brower
    attributes:
      label: If you selected Web, what brower are you seeing the problem on?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: What version of The House App are you seeing the problem on?
      description: Please make sure this issue is on the latest version of The House App before submitting.
      options:
        - Latest
        - Latest Testing Release
        - Website
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Lastly, add any other context about the problem here.
      # placeholder:
      # value:
    validations:
      required: false
