name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
# assignees:
# projects:
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to share your feedback. We value your input and use it to make The House App even better. Please be thoughtful and constructive with your comments. We appreciate your support!
  - type: textarea
    id: describe-the-feature
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
      # value:
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      # placeholder:
      # value:
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: If applicable, describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      # placeholder:
      # value:
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Lastly, add any other context or screenshots about the feature request here.
      # placeholder:
      # value:
    validations:
      required: false
